services:
  tests:
    image: samlockart/plugin-tester
    volumes:
      - ".:/plugin"
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'alam0rt/cosign']
    volumes:
      - ".:/plugin:ro"
