name: Cosign
description: Automate the signing of images and commits
author: https://github.com/alam0rt
requirements:
  - cosign
configuration:
  properties:
    mode:
      type: string
    image:
      type: string
    require:
      type: array
  additionalProperties: false
