name: Cosign
description: Automate the signing of images and commits
author: https://github.com/alam0rt
requirements:
  - cosign
configuration:
  properties:
    tags:
      type: array
    image:
      type: string
  additionalProperties: false
