#!/bin/bash
set -euo pipefail

cosign_version='v0.4.0'
cosign_url="https://github.com/sigstore/cosign/releases/download/${cosign_version}/cosign-linux-amd64"
cosign_executable=./cosign

mode="$BUILDKITE_PLUGIN_COSIGN_MODE"
pubkey="$BUILDKITE_PLUGIN_COSIGN_PUBKEY"
IMAGE="$BUILDKITE_PLUGIN_COSIGN_IMAGE"
TAGS="$BUILDKITE_PLUGIN_COSIGN_TAGS"


curl -Lf -o ${cosign_executable} $cosign_url && chmod +x ${cosign_executable}


if [[ $mode == "verify" ]]; then
  echo "--- :1234: Verify image"

  args=()
  args+=(verify -key ${pubkey})

  if [[ $TAGS != "" ]]; then
    args+=(-a $TAGS)
  fi

  echo ${cosign_executable} ${args[@]} $IMAGE
  ${cosign_executable} ${args[@]} $IMAGE

  #buildkite-agent annotate "Image $IMAGE - $type"
fi


if [[ $mode == "generate" ]]; then
  echo "--- :key: generate signature"
  args=()
  args+=(generate)

  for tag in $(env | grep BUILDKITE_BUILD); do
    args+=(-a "$tag")
  done

  ${cosign_executable} ${args[@]} $IMAGE > example/generated_signature.json
fi
